language: minimal

sudo: required
services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker tag vsuzdaltsev/docker-in-docker-ruby:latest
  - docker push vsuzdaltsev/docker-in-docker-ruby:latest
